version: "3.3"
services:
  magento2-app:
    build:
      context:     .
      dockerfile: ./Dockerfile
    image: magento2-php-nginx
    container_name: magento2-app
    links:
      - magento2-db
      - magento2-elasticsearch
    ports:
      - "8000:80"
      - "9000:9000"
  magento2-db:
    image: mariadb:10.4
    container_name: magento2_db
    environment:
      MYSQL_DATABASE: magento2_db
      MYSQL_ROOT_PASSWORD: test
  magento2-elasticsearch:
    image: elasticsearch:7.6.2
    container_name: magento2-elasticsearch
    environment:
      - discovery.type=single-node
